# Generated by Django 3.1.2 on 2020-11-07 16:57

import diploAdmin.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=255, verbose_name='Название модуля')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
                'db_table': 'modules',
            },
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('stage_id', models.AutoField(primary_key=True, serialize=False)),
                ('stage_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('start_date_fact', models.DateField()),
                ('finish_date_fact', models.DateField()),
                ('stage_module', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='diploAdmin.modules')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
                'db_table': 'stages',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_login', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Логин')),
                ('user_password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('sur_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone_num', models.CharField(max_length=255, unique=True, verbose_name='Номер телефона')),
                ('email_addr', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('logical_delete_status', models.BooleanField(default=False, verbose_name='Логическое удаление')),
                ('user_image_src', models.ImageField(blank=True, max_length=255, null=True, upload_to=diploAdmin.models.upload_location, verbose_name='Путь до аватарки пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Workgroups',
            fields=[
                ('workgroup_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код группы')),
                ('workgroup_name', models.CharField(max_length=255, unique=True, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Рабочая группа',
                'verbose_name_plural': 'Рабочие группы',
                'db_table': 'workgroups',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_login', models.OneToOneField(db_column='client_login', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='diploAdmin.users', verbose_name='Логин клиента')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('developer_login', models.OneToOneField(db_column='developer_login', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='diploAdmin.users', verbose_name='Логин разработчика')),
                ('outsource_spec', models.BooleanField(default=False, verbose_name='Внештатный разработчик')),
            ],
            options={
                'verbose_name': 'Разработчик',
                'verbose_name_plural': 'Разработчики',
                'db_table': 'developers',
            },
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('manager_login', models.OneToOneField(db_column='manager_login', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='diploAdmin.users', verbose_name='Логин менеджера')),
                ('outsource_spec', models.BooleanField(blank=True, choices=[(True, 'Да'), (False, 'Нет')], default=False, null=True, verbose_name='Главный менджер')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
                'db_table': 'managers',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='diploAdmin.tasks', verbose_name='Название главной задачи')),
                ('task_stage', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='diploAdmin.stages', verbose_name='Название этапа')),
                ('task_developer_login', models.ForeignKey(db_column='task_developer_login', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='diploAdmin.developers', verbose_name='Логин разработчика')),
            ],
            options={
                'verbose_name': 'Задачу',
                'verbose_name_plural': 'Задачи',
                'db_table': 'tasks',
            },
        ),
        migrations.AddField(
            model_name='stages',
            name='stage_status',
            field=models.ForeignKey(db_column='stage_status', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='diploAdmin.status'),
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(default='Плохой проект', max_length=255, verbose_name='Название проекта')),
                ('project_info', models.TextField(verbose_name='Информация о проекте')),
                ('start_date_plan', models.DateField(auto_now_add=True, null=True, verbose_name='Дата старта проекта')),
                ('finish_date_plan', models.DateField(verbose_name='Дата окончания проекта')),
                ('start_date_fact', models.DateField(auto_now_add=True, null=True, verbose_name='Фактическая дата старта проекта')),
                ('finish_date_fact', models.DateField(verbose_name='Фактический дата конца проекта')),
                ('tech_task_path', models.FileField(upload_to=diploAdmin.models.upload_location_tasks, verbose_name='Путь до экспортированных задач')),
                ('project_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='diploAdmin.status', verbose_name='Статус проекта')),
                ('project_workgroup', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='diploAdmin.workgroups', verbose_name='Рабоча группа')),
                ('project_client_login', models.ForeignKey(db_column='project_client_login', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='diploAdmin.clients', verbose_name='Логин клиента')),
                ('project_manager_login', models.ForeignKey(db_column='project_manager_login', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='diploAdmin.managers', verbose_name='Логин менеджера')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Organisations',
            fields=[
                ('organisation_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('organisation_description', models.TextField(blank=True, null=True)),
                ('organisation_image_src', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'db_table': 'organisations',
                'unique_together': {('full_name', 'short_name')},
            },
        ),
        migrations.AddField(
            model_name='modules',
            name='module_project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='diploAdmin.projects', verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='modules',
            name='module_status',
            field=models.ForeignKey(db_column='module_status', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='diploAdmin.status', verbose_name='Статус модуля'),
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_name', models.CharField(max_length=255, verbose_name='Название проблемы')),
                ('issue_description', models.TextField(verbose_name='Описание проблемы')),
                ('issue_date', models.DateField(verbose_name='Дата обьявления проблемы')),
                ('issue_close_status', models.BooleanField(blank=True, choices=[(True, 'Да'), (False, 'Нет')], default=False, null=True, verbose_name='Исправлено')),
                ('issue_task', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='diploAdmin.tasks', verbose_name='Название задачи')),
            ],
            options={
                'verbose_name': 'Проблема',
                'verbose_name_plural': 'Проблемы',
                'db_table': 'issues',
            },
        ),
        migrations.CreateModel(
            name='WorkingDeveloperList',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('head_status', models.BooleanField(verbose_name='Начальник')),
                ('workgroup', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='diploAdmin.workgroups', verbose_name='Рабочая группа')),
                ('developer_login', models.ForeignKey(db_column='developer_login', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='diploAdmin.developers', verbose_name='Логин разработчика')),
            ],
            options={
                'verbose_name': 'Список группы',
                'verbose_name_plural': 'Список групп',
                'db_table': 'working_developer_list',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note_name', models.CharField(max_length=255, verbose_name='Название')),
                ('note_desc', models.TextField(verbose_name='Описание')),
                ('note_date', models.DateField(auto_now_add=True, verbose_name='Дата создания заметки')),
                ('note_task_id', models.ForeignKey(db_column='note_task_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='diploAdmin.tasks', verbose_name='Название задачи')),
                ('note_client_login', models.ForeignKey(db_column='note_client_login', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='diploAdmin.clients', verbose_name='Логин клиента')),
            ],
            options={
                'verbose_name': 'Правка',
                'verbose_name_plural': 'Правки',
                'db_table': 'notes',
            },
        ),
        migrations.AddField(
            model_name='clients',
            name='client_organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='diploAdmin.organisations', verbose_name='Организация клиента'),
        ),
    ]
