# Generated by Django 3.1.2 on 2021-03-05 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diploAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='login_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил документ'),
        ),
    ]
