# Generated by Django 3.1.2 on 2021-02-22 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_num',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message="Телефон должен быть примерно такого формата: '+99999999999'. Содержать максимум 17 цифр.", regex='^\\+?1?\\d{9,17}$')], verbose_name='Номер телефона'),
        ),
    ]
