# Generated by Django 3.1.2 on 2020-11-07 17:11

import diploAdmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='tech_task_path',
            field=models.FileField(blank=True, null=True, upload_to=diploAdmin.models.upload_location_tasks, verbose_name='Путь до экспортированных задач'),
        ),
    ]
