# Generated by Django 3.1.2 on 2020-11-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploAdmin', '0002_auto_20201107_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='start_date_fact',
            field=models.DateField(auto_now_add=True, verbose_name='Фактическая дата старта проекта'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date_plan',
            field=models.DateField(auto_now_add=True, verbose_name='Дата старта проекта'),
        ),
    ]
