# Generated by Django 3.1.2 on 2021-03-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploAdmin', '0002_auto_20210305_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='docs_path',
            field=models.ManyToManyField(blank=True, null=True, to='diploAdmin.Documents', verbose_name='Документы'),
        ),
        migrations.AddField(
            model_name='modules',
            name='docs_path',
            field=models.ManyToManyField(blank=True, null=True, to='diploAdmin.Documents', verbose_name='Документы'),
        ),
        migrations.AddField(
            model_name='notes',
            name='docs_path',
            field=models.ManyToManyField(blank=True, null=True, to='diploAdmin.Documents', verbose_name='Документы'),
        ),
        migrations.AddField(
            model_name='stages',
            name='docs_path',
            field=models.ManyToManyField(blank=True, null=True, to='diploAdmin.Documents', verbose_name='Документы'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='docs_path',
            field=models.ManyToManyField(blank=True, null=True, to='diploAdmin.Documents', verbose_name='Документы'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='docs_path',
            field=models.ManyToManyField(blank=True, null=True, to='diploAdmin.Documents', verbose_name='Документы'),
        ),
    ]
