# Generated by Django 3.1.2 on 2021-02-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploAdmin', '0002_auto_20210223_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_active',
        ),
        migrations.AddField(
            model_name='users',
            name='is_Active',
            field=models.BooleanField(default=True, verbose_name='Активированный пользователь'),
        ),
    ]
