# Generated by Django 3.1.2 on 2021-03-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploAdmin', '0003_auto_20210305_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stages',
            name='finish_date',
            field=models.DateField(verbose_name='Дата окончания проекта'),
        ),
        migrations.AlterField(
            model_name='stages',
            name='finish_date_fact',
            field=models.DateField(verbose_name='Фактическая дата конца проекта'),
        ),
        migrations.AlterField(
            model_name='stages',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата старта проекта'),
        ),
        migrations.AlterField(
            model_name='stages',
            name='start_date_fact',
            field=models.DateField(verbose_name='Фактическая дата старта проекта'),
        ),
    ]
