# Generated by Django 3.1.2 on 2020-11-07 17:34

import diploAdmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploAdmin', '0003_auto_20201107_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisations',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Полное наименование организации'),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='organisation_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='organisation_image_src',
            field=models.ImageField(blank=True, null=True, upload_to=diploAdmin.models.upload_location_org, verbose_name='Путь до аватарки организации'),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Короткое наименование организации'),
        ),
    ]
