# Generated by Django 3.1.2 on 2021-03-05 13:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diploAdmin', '0004_auto_20210305_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='finish_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания задачи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='finish_date_fact',
            field=models.DateField(blank=True, null=True, verbose_name='Фактическая дата конца задачи'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата старта задачи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='start_date_fact',
            field=models.DateField(blank=True, null=True, verbose_name='Фактическая дата старта задачи'),
        ),
        migrations.AlterField(
            model_name='stages',
            name='finish_date',
            field=models.DateField(verbose_name='Дата окончания этапа'),
        ),
        migrations.AlterField(
            model_name='stages',
            name='finish_date_fact',
            field=models.DateField(verbose_name='Фактическая дата конца этапа'),
        ),
        migrations.AlterField(
            model_name='stages',
            name='stage_module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='diploAdmin.modules', verbose_name='Название модуля'),
        ),
        migrations.AlterField(
            model_name='stages',
            name='stage_name',
            field=models.CharField(max_length=255, verbose_name='Название этапа'),
        ),
        migrations.AlterField(
            model_name='stages',
            name='stage_status',
            field=models.ForeignKey(db_column='stage_status', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='diploAdmin.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='stages',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата старта этапа'),
        ),
        migrations.AlterField(
            model_name='stages',
            name='start_date_fact',
            field=models.DateField(verbose_name='Фактическая дата старта этапа'),
        ),
    ]
