# Generated by Django 3.1.2 on 2021-03-06 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diploAdmin', '0005_auto_20210305_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_setter_login',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Поставил задачу'),
        ),
    ]
