# Generated by Django 3.1.2 on 2021-03-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploAdmin', '0006_tasks_task_setter_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_name',
            field=models.CharField(default='Плохой проект', max_length=255, unique=True, verbose_name='Название проекта'),
        ),
    ]
