# Generated by Django 3.1.2 on 2021-03-16 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diploAdmin', '0007_auto_20210310_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_client_login',
            field=models.ForeignKey(db_column='project_client_login', default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diploAdmin.clients', verbose_name='Логин клиента'),
        ),
    ]
