# Generated by Django 3.1.2 on 2021-04-15 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diploAdmin', '0009_auto_20210316_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stages',
            name='docs_path',
        ),
        migrations.RemoveField(
            model_name='stages',
            name='stage_module',
        ),
        migrations.RemoveField(
            model_name='stages',
            name='stage_status',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='task_stage',
        ),
        migrations.AddField(
            model_name='tasks',
            name='project_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='diploAdmin.projects', verbose_name='К какому проекту относиться'),
        ),
        migrations.DeleteModel(
            name='Modules',
        ),
        migrations.DeleteModel(
            name='Stages',
        ),
    ]
