# Generated by Django 3.1.2 on 2021-04-21 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diploAdmin', '0010_auto_20210415_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='project_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diploAdmin.projects', verbose_name='К какому проекту относиться'),
        ),
    ]
