# Generated by Django 3.1.2 on 2021-05-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diploAdmin', '0012_tasks_description'),
        ('diploAdmin', '0012_tasks_task_status'),
    ]

    operations = [
    ]
