# Generated by Django 3.1.2 on 2021-05-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploAdmin', '0013_merge_20210505_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_Active',
            field=models.BooleanField(default=False, verbose_name='Активированный пользователь'),
        ),
    ]
